# Generated by Django 3.2.5 on 2022-07-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0004_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
